-- Strategy runtime configuration (global knobs/versioning).
create table if not exists public.strategy_runtime_config (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

insert into public.strategy_runtime_config (key, value)
values (
  'global',
  jsonb_build_object(
    'strategy_version', 'v2.0.0',
    'setup_label', 'setup_score',
    'account_equity_usd', 10000,
    'max_total_risk_pct', 2.0,
    'max_open_trades', 4,
    'max_trades_per_day', 10,
    'max_symbol_trades_per_day', 2,
    'max_trades_per_session', 4,
    'correlation_base_currency_cap', 2,
    'telegram_max_messages_per_hour', 8,
    'session_filter_enabled', true,
    'news_filter_enabled', false,
    'volatility_filter_enabled', true,
    'trend_filter_enabled', true
  )
)
on conflict (key) do nothing;

-- Per-symbol strategy configuration.
create table if not exists public.strategy_symbol_config (
  symbol text primary key,
  enabled boolean not null default true,
  strategy_version text not null default 'v2.0.0',
  trigger_policy text not null default 'market',
  session_start_hour_utc smallint not null default 6,
  session_end_hour_utc smallint not null default 22,
  risk_per_trade_pct numeric(6, 3) not null default 0.50,
  min_stop_pips numeric(10, 4) not null default 8.0,
  max_stop_pips numeric(10, 4) not null default 45.0,
  max_spread_pips numeric(10, 4) not null default 2.2,
  require_spread boolean not null default false,
  min_atr_pips numeric(10, 4) not null default 4.0,
  max_atr_pips numeric(10, 4) not null default 65.0,
  min_trend_strength numeric(10, 4) not null default 0.25,
  signal_ttl_hours integer not null default 6,
  reentry_cooldown_hours integer not null default 4,
  slippage_pips_assumed numeric(10, 4) not null default 0.4,
  tp1_take_pct numeric(5, 2) not null default 50.0,
  tp2_take_pct numeric(5, 2) not null default 30.0,
  tp3_take_pct numeric(5, 2) not null default 20.0,
  move_sl_to_be_on_tp1 boolean not null default true,
  trail_after_tp2 boolean not null default true,
  trail_atr_multiple numeric(10, 4) not null default 0.8,
  updated_at timestamptz not null default now(),
  constraint strategy_symbol_config_trigger_policy_check
    check (trigger_policy in ('market', 'limit', 'confirmation')),
  constraint strategy_symbol_config_hours_check
    check (session_start_hour_utc between 0 and 23 and session_end_hour_utc between 0 and 23),
  constraint strategy_symbol_config_risk_check
    check (risk_per_trade_pct > 0 and risk_per_trade_pct <= 5),
  constraint strategy_symbol_config_stop_check
    check (min_stop_pips > 0 and max_stop_pips >= min_stop_pips),
  constraint strategy_symbol_config_tp_pct_sum_check
    check (round((tp1_take_pct + tp2_take_pct + tp3_take_pct)::numeric, 2) = 100.00)
);

insert into public.strategy_symbol_config (symbol)
values
  ('EUR/USD'),
  ('GBP/USD'),
  ('USD/JPY'),
  ('USD/CHF'),
  ('AUD/USD'),
  ('USD/CAD'),
  ('NZD/USD'),
  ('EUR/JPY'),
  ('GBP/JPY'),
  ('EUR/GBP')
on conflict (symbol) do nothing;

-- Signal lifecycle table.
create table if not exists public.trading_signals (
  id bigint generated by default as identity primary key,
  signal_key text not null unique,
  check_id bigint references public.trading_opportunity_checks (id) on delete set null,
  trace_id text not null,
  symbol text not null,
  strategy_version text not null default 'v2.0.0',
  strategy_name text not null,
  setup_label text not null default 'setup_score',
  setup_score numeric(6, 3) not null default 0,
  direction text not null,
  signal_state text not null default 'pending',
  trigger_policy text not null default 'market',
  entry_price numeric(20, 10),
  stop_loss numeric(20, 10),
  tp1 numeric(20, 10),
  tp2 numeric(20, 10),
  tp3 numeric(20, 10),
  risk_r numeric(20, 10),
  risk_amount_usd numeric(20, 10),
  position_size_units numeric(24, 8),
  spread_pips numeric(10, 4),
  slippage_pips_assumed numeric(10, 4),
  news_flag boolean not null default false,
  regime_passed boolean not null default false,
  valid_from timestamptz not null default now(),
  valid_until timestamptz,
  triggered_at timestamptz,
  invalidated_at timestamptz,
  expired_at timestamptz,
  executed_at timestamptz,
  cooldown_until timestamptz,
  invalidation_reason text,
  last_evaluated_at timestamptz not null default now(),
  top_reasons jsonb not null default '[]'::jsonb,
  invalidation_conditions jsonb not null default '[]'::jsonb,
  management_plan jsonb not null default '{}'::jsonb,
  primary_plan jsonb not null default '{}'::jsonb,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trading_signals_direction_check
    check (direction in ('long', 'short', 'none')),
  constraint trading_signals_state_check
    check (
      signal_state in (
        'pending',
        'active',
        'triggered',
        'invalidated',
        'expired',
        'executed',
        'cancelled'
      )
    ),
  constraint trading_signals_trigger_policy_check
    check (trigger_policy in ('market', 'limit', 'confirmation'))
);

create index if not exists trading_signals_symbol_state_idx
  on public.trading_signals (symbol, signal_state, created_at desc);

create index if not exists trading_signals_valid_until_idx
  on public.trading_signals (signal_state, valid_until);

create index if not exists trading_signals_trace_idx
  on public.trading_signals (trace_id);

-- Lifecycle events/audit log per signal.
create table if not exists public.trading_signal_events (
  id bigint generated by default as identity primary key,
  signal_id bigint not null references public.trading_signals (id) on delete cascade,
  trace_id text not null,
  event_type text not null,
  from_state text,
  to_state text,
  event_reason text,
  event_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists trading_signal_events_signal_idx
  on public.trading_signal_events (signal_id, created_at desc);

create index if not exists trading_signal_events_trace_idx
  on public.trading_signal_events (trace_id, created_at desc);

-- Execution layer / position tracking.
create table if not exists public.trading_positions (
  id bigint generated by default as identity primary key,
  signal_id bigint not null unique references public.trading_signals (id) on delete cascade,
  trace_id text not null,
  symbol text not null,
  direction text not null,
  status text not null default 'open',
  entry_price numeric(20, 10) not null,
  stop_loss numeric(20, 10) not null,
  current_stop_loss numeric(20, 10) not null,
  tp1 numeric(20, 10),
  tp2 numeric(20, 10),
  tp3 numeric(20, 10),
  risk_amount_usd numeric(20, 10),
  planned_size_units numeric(24, 8),
  open_size_units numeric(24, 8),
  closed_size_units numeric(24, 8) not null default 0,
  tp1_hit_at timestamptz,
  tp2_hit_at timestamptz,
  tp3_hit_at timestamptz,
  moved_to_be_at timestamptz,
  trailing_active boolean not null default false,
  trailing_atr_multiple numeric(10, 4),
  broker text not null default 'paper',
  broker_order_id text,
  execution_payload jsonb not null default '{}'::jsonb,
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  close_reason text,
  realized_pnl numeric(20, 10),
  realized_r numeric(20, 10),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trading_positions_direction_check
    check (direction in ('long', 'short')),
  constraint trading_positions_status_check
    check (status in ('open', 'closed', 'cancelled'))
);

create index if not exists trading_positions_symbol_status_idx
  on public.trading_positions (symbol, status, opened_at desc);

create index if not exists trading_positions_trace_idx
  on public.trading_positions (trace_id);

-- Idempotent outbound notification log + spam guard.
create table if not exists public.telegram_notification_log (
  id bigint generated by default as identity primary key,
  signal_id bigint references public.trading_signals (id) on delete set null,
  symbol text not null,
  message_hash text not null,
  status text not null default 'pending',
  attempt_count integer not null default 1,
  sent_at timestamptz,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint telegram_notification_status_check
    check (status in ('pending', 'sent', 'failed', 'suppressed')),
  unique (symbol, message_hash)
);

create index if not exists telegram_notification_log_symbol_created_idx
  on public.telegram_notification_log (symbol, created_at desc);

-- Reliability / observability.
create table if not exists public.ops_function_runs (
  id bigint generated by default as identity primary key,
  function_name text not null,
  trace_id text not null,
  status text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_ms integer,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint ops_function_runs_status_check
    check (status in ('started', 'success', 'failed', 'partial'))
);

create index if not exists ops_function_runs_function_started_idx
  on public.ops_function_runs (function_name, started_at desc);

create table if not exists public.ops_alerts (
  id bigint generated by default as identity primary key,
  trace_id text,
  alert_type text not null,
  severity text not null default 'warning',
  message text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint ops_alerts_severity_check
    check (severity in ('info', 'warning', 'error', 'critical'))
);

create index if not exists ops_alerts_created_idx
  on public.ops_alerts (created_at desc);

-- Validation/backtest result storage.
create table if not exists public.strategy_validation_runs (
  id bigint generated by default as identity primary key,
  trace_id text not null,
  strategy_version text not null,
  symbol text not null,
  timeframe text not null default '1h',
  from_time timestamptz not null,
  to_time timestamptz not null,
  walk_forward_split timestamptz,
  metrics jsonb not null default '{}'::jsonb,
  calibration jsonb not null default '{}'::jsonb,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists strategy_validation_runs_symbol_created_idx
  on public.strategy_validation_runs (symbol, created_at desc);

-- Extend checks with lifecycle/risk fields for reproducibility.
alter table public.trading_opportunity_checks
  add column if not exists setup_label text not null default 'setup_score',
  add column if not exists setup_score numeric(6, 3) not null default 0,
  add column if not exists strategy_version text not null default 'v2.0.0',
  add column if not exists signal_state text not null default 'none',
  add column if not exists signal_id bigint,
  add column if not exists trigger_policy text,
  add column if not exists expires_at timestamptz,
  add column if not exists dedupe_key text,
  add column if not exists trace_id text,
  add column if not exists top_reasons jsonb not null default '[]'::jsonb,
  add column if not exists invalidation_conditions jsonb not null default '[]'::jsonb,
  add column if not exists primary_plan jsonb not null default '{}'::jsonb,
  add column if not exists spread_pips numeric(10, 4),
  add column if not exists news_nearby boolean not null default false,
  add column if not exists regime_passed boolean not null default false;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'trading_opportunity_checks_signal_state_check'
      and conrelid = 'public.trading_opportunity_checks'::regclass
  ) then
    alter table public.trading_opportunity_checks
      add constraint trading_opportunity_checks_signal_state_check
      check (
        signal_state in (
          'none',
          'pending',
          'active',
          'triggered',
          'invalidated',
          'expired',
          'executed',
          'cancelled'
        )
      );
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'trading_opportunity_checks_signal_fk'
      and conrelid = 'public.trading_opportunity_checks'::regclass
  ) then
    alter table public.trading_opportunity_checks
      add constraint trading_opportunity_checks_signal_fk
      foreign key (signal_id) references public.trading_signals (id) on delete set null;
  end if;
end;
$$;

create index if not exists trading_opportunity_checks_signal_idx
  on public.trading_opportunity_checks (symbol, signal_state, latest_candle_time desc);

create index if not exists trading_opportunity_checks_trace_idx
  on public.trading_opportunity_checks (trace_id);

-- Helper to expire stale signals in batch.
create or replace function public.expire_stale_signals(p_now timestamptz default now())
returns integer
language plpgsql
as $$
declare
  v_count integer := 0;
begin
  update public.trading_signals
  set signal_state = 'expired',
      expired_at = p_now,
      updated_at = p_now
  where signal_state in ('pending', 'active')
    and valid_until is not null
    and valid_until <= p_now;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;
