create table if not exists public.broker_oauth_tokens (
  id bigint generated by default as identity primary key,
  provider text not null,
  connection_key text not null default 'default',
  access_token text not null,
  refresh_token text,
  token_type text,
  scope text,
  ctrader_account_id text,
  expires_in_seconds integer,
  access_token_expires_at timestamptz,
  oauth_state text,
  status text not null default 'active',
  raw_response jsonb not null default '{}'::jsonb,
  last_refreshed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint broker_oauth_tokens_status_check
    check (status in ('active', 'revoked', 'error')),
  unique (provider, connection_key)
);

create index if not exists broker_oauth_tokens_provider_status_idx
  on public.broker_oauth_tokens (provider, status, updated_at desc);

create index if not exists broker_oauth_tokens_expiry_idx
  on public.broker_oauth_tokens (access_token_expires_at);
