create table if not exists public.broker_callback_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_id text not null,
  trace_id text not null,
  intent_id bigint,
  signal_id bigint,
  broker_order_id text,
  processing_status text not null default 'received',
  error text,
  payload jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint broker_callback_events_processing_status_check
    check (processing_status in ('received', 'processed', 'ignored', 'error', 'duplicate')),
  unique (provider, event_id)
);

create index if not exists broker_callback_events_received_idx
  on public.broker_callback_events (received_at desc);

create index if not exists broker_callback_events_intent_idx
  on public.broker_callback_events (intent_id, received_at desc);

create index if not exists broker_callback_events_broker_order_idx
  on public.broker_callback_events (broker_order_id, received_at desc);
