-- Extend runtime config with session-level trade cap if missing.
insert into public.strategy_runtime_config (key, value)
values ('global', jsonb_build_object('max_trades_per_session', 4))
on conflict (key) do nothing;

update public.strategy_runtime_config
set value = jsonb_set(
  coalesce(value, '{}'::jsonb),
  '{max_trades_per_session}',
  coalesce(value->'max_trades_per_session', to_jsonb(4)),
  true
),
updated_at = now()
where key = 'global';

-- Broker execution queue (execution layer foundation).
create table if not exists public.broker_order_intents (
  id bigint generated by default as identity primary key,
  signal_id bigint references public.trading_signals (id) on delete set null,
  trace_id text not null,
  symbol text not null,
  direction text not null,
  order_type text not null default 'market',
  requested_entry_price numeric(20, 10),
  stop_loss numeric(20, 10),
  tp1 numeric(20, 10),
  tp2 numeric(20, 10),
  tp3 numeric(20, 10),
  planned_size_units numeric(24, 8),
  status text not null default 'pending',
  broker text not null default 'paper',
  broker_order_id text,
  request_payload jsonb not null default '{}'::jsonb,
  response_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint broker_order_intents_direction_check
    check (direction in ('long', 'short')),
  constraint broker_order_intents_order_type_check
    check (order_type in ('market', 'limit', 'stop')),
  constraint broker_order_intents_status_check
    check (
      status in (
        'pending',
        'sent',
        'acknowledged',
        'filled',
        'partially_filled',
        'cancelled',
        'rejected',
        'error'
      )
    )
);

create index if not exists broker_order_intents_status_idx
  on public.broker_order_intents (status, created_at desc);

create index if not exists broker_order_intents_signal_idx
  on public.broker_order_intents (signal_id, created_at desc);

-- Snapshots pulled from broker API to reconcile open/closed positions with local DB.
create table if not exists public.broker_position_sync_snapshots (
  id bigint generated by default as identity primary key,
  trace_id text not null,
  broker text not null,
  broker_position_id text not null,
  symbol text not null,
  direction text not null,
  quantity numeric(24, 8),
  avg_price numeric(20, 10),
  stop_loss numeric(20, 10),
  take_profit numeric(20, 10),
  status text not null default 'open',
  snapshot_time timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint broker_position_sync_direction_check
    check (direction in ('long', 'short')),
  constraint broker_position_sync_status_check
    check (status in ('open', 'closed', 'cancelled'))
);

create index if not exists broker_position_sync_symbol_time_idx
  on public.broker_position_sync_snapshots (symbol, snapshot_time desc);

create index if not exists broker_position_sync_broker_position_idx
  on public.broker_position_sync_snapshots (broker, broker_position_id, snapshot_time desc);

-- Helper to enqueue an execution intent directly from a signal.
create or replace function public.enqueue_broker_order_from_signal(
  p_signal_id bigint,
  p_trace_id text default null
)
returns bigint
language plpgsql
as $$
declare
  v_signal public.trading_signals%rowtype;
  v_trace text;
  v_order_id bigint;
  v_order_type text;
begin
  select *
    into v_signal
  from public.trading_signals
  where id = p_signal_id;

  if not found then
    raise exception 'Signal % not found', p_signal_id;
  end if;

  if v_signal.direction not in ('long', 'short') then
    raise exception 'Signal % has invalid direction %', p_signal_id, v_signal.direction;
  end if;

  v_trace := coalesce(nullif(p_trace_id, ''), v_signal.trace_id);
  v_order_type := case
    when v_signal.trigger_policy = 'limit' then 'limit'
    when v_signal.trigger_policy = 'market' then 'market'
    else 'market'
  end;

  insert into public.broker_order_intents (
    signal_id,
    trace_id,
    symbol,
    direction,
    order_type,
    requested_entry_price,
    stop_loss,
    tp1,
    tp2,
    tp3,
    planned_size_units,
    broker,
    request_payload
  ) values (
    v_signal.id,
    v_trace,
    v_signal.symbol,
    v_signal.direction,
    v_order_type,
    v_signal.entry_price,
    v_signal.stop_loss,
    v_signal.tp1,
    v_signal.tp2,
    v_signal.tp3,
    v_signal.position_size_units,
    'paper',
    jsonb_build_object(
      'source', 'enqueue_broker_order_from_signal',
      'signal_state', v_signal.signal_state,
      'strategy_version', v_signal.strategy_version
    )
  )
  returning id into v_order_id;

  return v_order_id;
end;
$$;
