create table if not exists public.trading_opportunity_checks (
  id bigint generated by default as identity primary key,
  symbol text not null,
  checked_at timestamptz not null default now(),
  latest_price numeric(20, 10) not null,
  latest_candle_time timestamptz,
  signal text not null,
  confidence numeric(5, 4) not null default 0,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint trading_opportunity_checks_signal_check
    check (signal in ('long_candidate', 'short_candidate', 'none'))
);

create index if not exists trading_opportunity_checks_symbol_checked_at_idx
  on public.trading_opportunity_checks (symbol, checked_at desc);
